# Copyright 2018 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

default:
	pub run bin/main.dart abc 123 456 hello

fmt:
	dartfmt -w .

test:

clean:
